### ISSUE TITLE
Installation impossible

### ISSUE THREAD

**Issue by hanynowsky** [gescheit/fastsnmp#1]
Hello,

How would you install fastsnmp using pip?

**Comment by gescheit** [comment]
Try:
# pip install fastsnmp

**Comment by hanynowsky** [comment]
hello. Thanks for the reply.
This is what I have been trying to do but in vain. Using pip. It's a CentOS 6.6 VM, using Python3.4
I always get an error message saying there is not matched distribution:
```
# pip search fastsnmp
fastsnmp     - SNMP poller oriented to poll bunch of hosts in short time. Package include poller and SNMP library
```
And

```
# pip install fastsnmp
  Could not find a version that satisfies the requirement fastsnmp (from versions: )
No matching distribution found for fastsnmp

```

To install FastSNMP I ended up doing it manually, using:
```
python setup.py install
```

**Comment by gescheit** [comment]
Seems there is pip >1.4 that do not installing not stable packages by default. Try pip --pre install fastsnmp
